<div class="modal fade" id="cg" tabindex="-1" aria-labelledby="cg" aria-hidden="true">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Conditions générales</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div>
                    <div class="content" id="article_content">
                        <p class="text-center">(Conditions d’Utilisation révisées en date du 10/06/2021)</p>
                        <p><strong>PRÉAMBULE</strong></p>
                        <p>Les présentes Conditions d’Utilisation des Services sont conclues entre la société Love and heart (ci-après&nbsp;<strong>«&nbsp;Love and heart&nbsp;»</strong>) et toute personne ayant la qualité de Membre ou Abonné (ci-après également&nbsp;<strong>«&nbsp;vous&nbsp;»</strong>,&nbsp;<strong>«&nbsp;votre&nbsp;»</strong>,&nbsp;<strong>«&nbsp;vos&nbsp;»</strong>).</p>
                        <p>Love and heart et les sociétés membres de son Groupe fournissent, sur les réseaux de communications électroniques, un ensemble de services ayant pour objet de favoriser les rencontres entre personnes à des fins personnelles, de loisirs et non commerciales (ci-après les&nbsp;<strong>«&nbsp;Services&nbsp;»</strong>), incluant notamment :</p>
                        <ul>
                            <li><strong>Love and heart</strong>, accessible aux Membres et Abonnés de Love and heart par internet ou applications mobiles.</li>
                        </ul>
                        <p>Pour chacun des Services, certaines fonctionnalités sont accessibles gratuitement par les Membres et d’autres fonctionnalités sont payantes et accessibles aux seuls Abonnés.</p>
                        <p>En créant un compte, le Membre ou l’Abonné reconnaît qu’il est pleinement informé et lié par toutes les dispositions (i) des Conditions d’utilisation, (ii) de notre&nbsp;politique de confidentialité, de notre&nbsp;Politique en matière de cookies&nbsp;et de nos&nbsp;Règles de communauté, chacune étant intégrée par renvoi dans les présentes Conditions d’utilisation, et par toutes conditions supplémentaires divulguées et acceptées par le Membre ou l’Abonné lors de l’achat de Services payants proposés avec les Services, celles-ci constituant un accord entre ledit Membre ou Abonné et Love and heart. Dans le cas où un Membre ou un Abonné n’accepte pas d’être lié par l’ensemble des modalités de ces Conditions d’utilisation, il doit cesser d’utiliser les services.</p>
                        <p>Les Conditions d’Utilisation sont la propriété de Love and heart et du Groupe. En conséquence, toute diffusion, exploitation, représentation, reproduction ou autre utilisation, totale ou partielle, sur tout support, des Conditions d’Utilisation à des fins autres que strictement personnelles et non professionnelles, est soumise à l’autorisation préalable de Love and heart. A défaut de cette autorisation, le contrevenant s’expose aux poursuites pénales et civiles prévues par la loi.</p>
                        <p><strong><u>ARTICLE 1. DÉFINITIONS</u></strong></p>
                        <p>Dans les Conditions d’Utilisation, les mots ou expressions commençant par une majuscule auront la signification suivante :</p>
                        <p><strong>«&nbsp;Abonnement&nbsp;»</strong>&nbsp;désigne un forfait payant donnant accès aux Services, en ce inclus les Services Payants sur une période limitée spécifiée dans l’Abonnement concerné souscrit par un Abonné.</p>
                        <p><strong>«&nbsp;Abonné&nbsp;»</strong>&nbsp;désigne un utilisateur d’un ou plusieurs Services ayant valablement souscrit un Abonnement à un ou plusieurs Services.</p>
                        <p><strong>«&nbsp;Event&nbsp;»&nbsp;</strong>ou&nbsp;<strong>«&nbsp;Activité&nbsp;»</strong>&nbsp;ou&nbsp;<strong>«&nbsp;Sortie&nbsp;»</strong>&nbsp;désigne, indifféremment et selon le Site délivrant le Service, tout évènement, gratuit ou payant, permettant aux Membres et Abonnés et, le cas échéant à leurs Invités de se rencontrer dans la vie réelle.</p>
                        <p><strong>«&nbsp;Membre&nbsp;»</strong>&nbsp;désigne un utilisateur bénéficiant d’un accès à l’un des Services après s’être inscrit gratuitement sur les Sites.</p>
                        <p><strong>«&nbsp;Option&nbsp;»</strong>&nbsp;désigne tout Service Payant autre qu’un Abonnement.</p>
                        <p><strong>«&nbsp;Profil&nbsp;»&nbsp;</strong>désigne un espace mis à disposition d’un Membre ou Abonné, comprenant la description qu’un Membre ou Abonné fait de lui-même en incluant des caractéristiques, photos et vidéos et qui est accessible à d’autres Membres et Abonnés.</p>
                        <p><strong>«&nbsp;Compte&nbsp;»&nbsp;</strong>désigne l’interface strictement personnelle accessible aux Membres et aux Abonnés, leur permettant de s’identifier sur les Sites, de bénéficier des Services auxquels ils se sont inscrits ou abonnés, de renseigner et de modifier leur Profil et, le cas échéant, de renouveler ou modifier l’Abonnement.</p>
                        <p><strong>«&nbsp;Services&nbsp;»</strong>&nbsp;désigne l’ensemble des services, payants ou gratuits, accessibles aux Membres ou aux Abonnés, proposés sur les Sites du Groupe.</p>
                        <p><strong>«&nbsp;Services Payants&nbsp;»</strong>&nbsp;désigne l’ensemble des Services payants accessibles aux Abonnés, en ce inclus les Options.</p>
                        <p><strong>«&nbsp;Sites&nbsp;»</strong>&nbsp;désigne tout site de rencontre proposé par une société du Groupe, comprenant les Sites Core Dating et les Sites Spécialisés, ainsi que les applications mobiles éditées par les sociétés du Groupe et à travers lesquels sont fournis des Services.</p>
                        <p><strong>«&nbsp;Visiteur&nbsp;»</strong>&nbsp;désigne un utilisateur qui visite le Site sans s’y être préalablement inscrit ou sans être connecté à son Compte.</p>
                        <p><strong>«&nbsp;Conditions d’Utilisation&nbsp;»</strong>&nbsp;désigne le présent contrat.</p>
                        <p><strong><u>ARTICLE 2. ACCÈS, INSCRIPTION ET ABONNEMENT</u></strong></p>
                        <p><strong><u>2.1. Procédure et conditions d’accès et d’inscription aux Services</u></strong></p>
                        <p>L’inscription aux Services est gratuite.</p>
                        <p>L’acceptation des Conditions d’Utilisation lors de l’inscription formalise la conclusion du contrat d’adhésion aux Services. Elle permet de devenir Membre, de découvrir les Services et donne accès aux fonctionnalités gratuites des Services décrites à l’article 4.1 ci-après.</p>
                        <p>Les Services sont exclusivement destinés aux adultes de plus de 18 ans.</p>
                        <p>Si un Membre ou un Abonné a moins de 18 ans, il n’est pas autorisé à utiliser les Services et doit immédiatement en cesser l’utilisation.</p>
                        <p>En créant un Profil et en utilisant les Services, les Membres et les Abonnés déclarent et certifient ce qui suit&nbsp;:</p>
                        <ul>
                            <li>ils ont plus de 18 ans et peuvent conclure un contrat juridiquement contraignant avec Love and heart..</li>
                            <li>ils remplissent les conditions d’inscription énoncées pour les Services concernés à tout moment.</li>
                            <li>ils se conforment aux présentes Conditions d’utilisation et à toutes les lois et réglementations applicables.</li>
                            <li>ils se conforment aux&nbsp;Règles de communauté</li>
                            <li>ils fournissent des informations correctes, exactes et véridiques ne prêtant pas à confusion. En particulier, ils doivent être sincères et honnêtes dans les réponses qu’ils fournissent sur leur profil et lorsqu’ils interagissent avec d’autres utilisateurs ou avec Love and heart et son Groupe.</li>
                            <li>ils respectent l’objectif des Services, qui est de permettre aux personnes de discuter à des fins personnelles, de divertissement et non commerciales, avec pour objectif général de rechercher une relation authentique.</li>
                            <li>ils mettent à jour, suspendent ou suppriment rapidement leur profil dans le cas où leur situation personnelle change et ils ne peuvent plus être qualifiés de célibataires.</li>
                            <li>ils ne se sont pas vus interdits d’utiliser les Services en vertu des lois applicables.</li>
                        </ul>
                        <p>Love and heart se réserve le droit de refuser, suspendre ou résilier l’adhésion ou l’abonnement à tout moment si un Membre ou un Abonné ne remplit aucune de ces conditions.</p>
                        <p>Il est précisé qu’un Membre ne peut pas créer plusieurs Comptes avec une même adresse email.</p>
                        <p>Une fois inscrit, le Membre complète son Profil, les informations étant fournies à titre facultatif ou obligatoire, le cas échéant. Ces informations sont publiées sur le Site et diffusées auprès des autres Membres au travers des Services. La diffusion par le Membre de ses coordonnées personnelles (adresse électronique, adresse postale, téléphone, etc.) est expressément prohibée par Love and heart (voir article 5.1 ci-après).</p>
                        <p>Lorsque les conditions nécessaires à l’inscription sont remplies, chaque Membre dispose d’un identifiant et d’un mot de passe strictement confidentiel et personnel lui permettant d’accéder à son Compte.</p>
                        <p>Le Membre ou l’Abonné est responsable de l’utilisation des éléments d’identification par des tiers ou des actions ou déclarations faites par l’intermédiaire de son Compte, qu’elles soient frauduleuses ou non, et garantit Love and heart contre toute demande à ce titre, sauf en cas de faute exclusivement imputable à Love and heart ou de défaillance technique du Services. Par ailleurs, Love and heart n’a pas pour obligation et ne s’assure pas de l’identité des personnes s’inscrivant aux Services. Si le Membre ou l’Abonné a des raisons de penser qu’une personne utilise ses éléments d’identification ou son Compte, il devra en informer immédiatement Love and heart.</p>
                        <p><strong><u>2.2.&nbsp;Procédure et conditions d’abonnement</u></strong></p>
                        <p>L’Abonnement aux Services, avec ou sans Option, est payant. Le Membre a la possibilité de souscrire un Abonnement et, ainsi, de devenir Abonné et bénéficier des fonctionnalités propres au type d’Abonnement choisi.</p>
                        <p>Pour ce faire, le Membre doit préalablement s’identifier à l’aide de son adresse email et de son mot de passe confidentiel. Après avoir choisi son Abonnement et son moyen de paiement, le Membre doit valider son paiement. Cette dernière étape formalise la conclusion du contrat d’adhésion aux Services Payants et l’acceptation sans réserve de l’intégralité des Conditions d’Utilisation. Une fois le paiement validé, l’Abonné est dirigé vers une page de confirmation de paiement. Love and heart accuse également réception de l’achat d’un Abonnement par courrier électronique.</p>
                        <p><strong><u>ARTICLE 3. DROIT DE RÉTRACTATION</u></strong></p>
                        <p>Conformément à l’article L.221-18 du Code de la Consommation, l’Abonné est informé qu’il dispose d’un délai de quatorze jours à compter du jour de la souscription d’un Abonnement pour exercer son droit de rétractation, sans pénalité et sans motif, ou au moyen d’une déclaration dénuée d’ambiguïté envoyée à l’adresse&nbsp;<a href="mailto:contact@love-and-heart.fr">contact@love-and-heart.fr</a>. Seules les demandes liées à l’exercice du droit de rétractation seront traitées à partir de ces adresses de contact. Pour que la rétractation soit effective, l’Abonné doit faire parvenir sa demande avant l’expiration du délai de rétractation de quatorze jours.</p>
                        <p>L’Abonné peut, s’il le souhaite, accéder immédiatement aux Services Payants sans attendre la fin du délai de rétractation, conformément à l’article L.221-25 du Code la Consommation. Un bouton spécifique est disponible sur la page de confirmation de paiement.</p>
                        <p>Si l’Abonné ne souhaite pas avoir immédiatement accès aux Services Payants, il peut quitter le Site après validation de son paiement et attendre l’expiration du délai de quatorze jours. Néanmoins, si l’Abonné se connecte à son Compte et utilise les Services avant l’expiration de ce délai, cette première connexion à compter de la souscription d’un Abonnement constitue une demande expresse de l’Abonné d’avoir immédiatement accès aux Services Payants.</p>
                        <p>Dans tous les cas, l’accès immédiat aux Services ne prive pas l’Abonné de son droit de rétractation, qui continue à courir jusqu’à l’expiration du délai de quatorze jours. Toutefois, l’Abonné ayant demandé à bénéficier des Services Payants avant la fin du délai de rétractation devra payer un montant proportionnel à son utilisation des Services. Love and heart remboursera alors à l’Abonné le prix de l’Abonnement déduction faite du montant correspondant au nombre de jours écoulés entre le jour de la première utilisation de l’Abonnement et celui de la réception par Love and heart de la demande de rétractation, étant précisé que tout jour débuté est dû.</p>
                        <p>Le remboursement interviendra dans un délai de quatorze jours à compter de la date à laquelle Love and heart a été informée de la décision de l’Abonné de se rétracter, par le même moyen de paiement que celui utilisé par l’Abonné pour la transaction initiale, sauf instruction contraire de ce dernier.</p>
                        <p>&nbsp;</p>
                        <p><strong><u>ARTICLE 4. FONCTIONNALITÉS DES SERVICES</u></strong></p>
                        <p><strong><u>4.1 Fonctionnalités gratuites accessibles aux Membres</u></strong></p>
                        <p>L’inscription aux Services permet de devenir Membre et donne accès à certaines fonctionnalités gratuites. Les fonctionnalités ne sont pas les mêmes selon les Services et peuvent évoluer dans le temps. L’inscription gratuite ne permet pas d’utiliser toutes les fonctionnalités du site. Selon les Services et sous réserve des éventuelles restrictions définies par les Membres, les fonctionnalités gratuites incluent notamment&nbsp;la création du Profil, certaines fonctionnalités de recherche, la consultation des Profils des autres Membres et l’inscription aux Events et Activités. La communication avec d’autres Membres nécessite généralement la souscription d’un Abonnement.</p>
                        <p>Chaque Membre peut contrôler, depuis son Compte, les paramètres lui permettant d’être visible ou non sur les Sites Spécialisés et ainsi de pouvoir être contacté, le cas échéant, sur ceux-ci. Un Membre pourra accéder aux Sites spécialisés à condition de satisfaire les conditions applicables aux Membres dudit Site Spécialisé.</p>
                        <p><strong><u>4.2 Fonctionnalités payantes accessibles aux seuls Abonnés</u></strong></p>
                        <p>La souscription d’un Abonnement donne accès aux fonctionnalités décrites sur le Site. Le cas échéant, des Options complémentaires peuvent êtres souscrites. Les fonctionnalités propres à ces Options sont également décrites sur le Site concerné.</p>
                        <p><strong><u>4.3 Souscription au « Badge »</u></strong></p>
                        <p>Cette section ne s’applique qu’aux Sites pour lesquels cette fonctionnalité est disponible.</p>
                        <p>Tout Membre ou Abonné de sexe masculin a la possibilité de souscrire au « Badge ». Le processus de souscription au Badge est le suivant :</p>
                        <ul>
                            <li>Le Membre ou Abonné doit compléter son Profil à 70% sur les critères suivants: âge, taille, situation maritale, type de relation recherché, nationalité, ethnicité, a des enfants ou souhait d’enfants, silhouette, fumeur, études</li>
                            <li>Le Membre doit ajouter une photo sur son profil</li>
                            <li>Le Membre doit visionner les tutoriels Love and heart relatifs au Badge disponibles sur les Sites</li>
                            <li>Le Membre doit signer la Charte du Gentleman Célibataire disponible sur les Sites</li>
                        </ul>
                        <p>L’obtention d’un Badge est soumise au respect de chacune des conditions visées ci-dessus.</p>
                        <p>Love and heart pourra retirer le Badge à tout Membre ou Abonné dont le comportement ou les propos portent atteinte aux valeurs de sérieux et de courtoisie résultant de l’obtention du Badge. La responsabilité de Love and heart ne pourra pas être recherchée par un Membre ou Abonné dans une telle hypothèse. Love and heart n’offre aucune garantie à l’égard du titulaire du Badge, autre que le respect des conditions de délivrance desdits badges ci-avant énoncées. L’obtention d’un Badge ne pourra être interprétée comme une approbation par le Groupe du comportement du titulaire du badge.</p>
                        <p>Dans le cas où la responsabilité de Love and heart serait recherchée par un tiers à raison de tout manquement par un Membre ou Abonné titulaire d’un Badge, ce dernier s’engage à garantir Love and heart contre toutes réclamations, actions, dommages, frais ou condamnations prononcés à son encontre et trouvant son origine dans le manquement imputé au Membre ou Abonné en relation avec la souscription à un Badge.</p>
                        <p><strong><u>ARTICLE 5. SERVICES</u></strong></p>
                        <p><strong><u>5.1. Obligations de</u></strong><strong>&nbsp;<u>Love and heart&nbsp;liées aux Services</u></strong></p>
                        <p>L’objet des Services, en ce inclus les Services Payants, n’est pas l’organisation de rencontres «&nbsp;réelles&nbsp;» entre les Membres et/ou Abonnés, ni le conseil ou le courtage matrimonial en vue de la réalisation d’un mariage ou l’établissement d’une union stable, quelles que soient les motivations personnelles animant un Membre ou un Abonné à cet égard.</p>
                        <p>Love and heart et les sociétés du Groupe excluent expressément toute responsabilité à l’égard des évènements de toute nature qui pourraient survenir lors de rencontres entre Membres ou Abonnés sur les Services ou lors de rencontres «&nbsp;réelles&nbsp;» entre Membres ou Abonnés à la suite de l’utilisation des Services.</p>
                        <p>L’objet des Services, en ce inclus les Services Payants, n’est pas la fourniture d’un accès au réseau Internet, ni la fourniture d’un service de communication électronique au public. En conséquence, Love and heart et les sociétés du Groupe ne contrôlent pas l’identité réelle des Membres ou des Abonnés lorsqu’ils se connectent aux Sites. Par ailleurs, elles ne contrôlent ni ne modèrent de façon exhaustive les contenus de toute nature que les Membres et Abonnés peuvent éditer sur les Services sous leur responsabilité exclusive. Néanmoins, les photographies et la description figurant sur le Profil de chaque Membre ou Abonné font l’objet d’une vérification.</p>
                        <p>Dans ce cadre, il est rappelé aux Membres et aux Abonnés qu’il leur est interdit de divulguer aux autres Membres ou Abonnés, par l’intermédiaire des Services, toute information permettant leur identification ou leur localisation (nom de famille, adresse postale, email, téléphone…), à l’exception de leur pseudonyme.</p>
                        <p><strong><u>5.2. Obligations des Membres et Abonnés</u></strong></p>
                        <p>En utilisant le Service, les Membres et les Abonnés doivent respecter à tout moment les règles de conduite suivantes et conviennent de ne pas&nbsp;:</p>
                        <ul>
                            <li>enfreindre nos&nbsp;Règles de communauté, mises à jour de temps à autre.</li>
                            <li>publier leurs coordonnées personnelles ou diffuser les informations personnelles d’une autre personne (adresse e-mail, adresse postale, numéro de téléphone, etc.) de quelque manière que ce soit (dans une description de profil, sur une photo, etc.)</li>
                            <li>publier tout contenu qui viole ou enfreint les droits d’autrui, y compris ceux relatifs à la publicité, vie privée, droits d’auteur, marques déposées ou tout autre droit de propriété intellectuelle ou contractuel.</li>
                            <li>usurper l’identité de toute personne ou entité.</li>
                            <li>solliciter des mots de passe à quelque fin que ce soit ou des informations d’identification personnelle à des fins commerciales ou illégales auprès d’autres Membres ou Abonnés.</li>
                            <li>spammer, demander de l’argent ou escroquer un Membre ou un Abonné.</li>
                            <li>publier tout contenu à caractère haineux, menaçant, sexuellement explicite ou pornographique&nbsp;; qui incite à la violence ou contient de la nudité ou de la violence explicite ou gratuite.</li>
                            <li>publier tout contenu qui promeuve le racisme, le sectarisme, la haine ou les dommages physiques de quelque nature que ce soit contre un groupe ou un individu.</li>
                            <li>malmener, «&nbsp;traquer&nbsp;», intimider, agresser, harceler, maltraiter ou diffamer toute personne.</li>
                            <li>utiliser les Services à des fins nuisibles ou malveillantes.</li>
                            <li>utiliser les Services afin de nuire à Love and heart ou à son Groupe.</li>
                            <li>utiliser les Services à des fins illégales ou interdites par les présentes Conditions d’utilisation.</li>
                            <li>utiliser les Services pour faire la promotion ou encourager des relations de nature transactionnelle et/ou des services sexuels commerciaux et/ou des actes sexuels non consensuels.</li>
                            <li>utiliser tout(e) logiciels, scripts, robots ou tout autre moyen ou processus (notamment des robots d’indexation, des modules d’extension de navigateur et compléments, ou toute autre technologie) visant à accéder, extraire, indexer, fouiller les données ou reproduire ou éluder de quelque façon que ce soit la structure de navigation ou la présentation du Service ou de ses contenus.</li>
                            <li>utiliser le compte d’un autre utilisateur, partager un compte avec un autre utilisateur ou gérer plusieurs comptes.</li>
                            <li>créer un autre compte si Love and heart ou son Groupe ont déjà résilié leur compte, à moins que le Membre ou l’Abonné n’ait l’autorisation de Love and heart.</li>
                            <li>utiliser les Services de mauvaise foi.</li>
                        </ul>
                        <p>Une violation par un Membre ou un Abonné de l’une de ces règles de conduite constitue une violation grave de ses obligations contractuelles en vertu des présentes Conditions d’utilisation.</p>
                        <p>Love and heart se réserve le droit de résilier le compte d’un Membre ou d’un Abonné sans aucun remboursement des Services payants en cas de violation des présentes obligations, d’utilisation abusive des Services ou de comportement, action ou communication inapproprié ou illégal survenu dans le cadre de l’utilisation des Services ou non. En outre, Love and heart peut interdire définitivement ou temporairement son accès à l’un de ses Services, Événements ou Activités.</p>
                        <p><strong><u>ARTICLE 6. PRIX, MODALITÉS DE PAIEMENT ET DE RENOUVELLEMENT</u></strong></p>
                        <p><strong><u>6.1. Prix et modalités de paiement des Services Payants</u></strong></p>
                        <p>Les prix et les modalités de paiement sont décrits sur les Sites. Le paiement s’effectue soit par carte bancaire (sur internet ou sur un service mobile), soit au moyen d’un service de paiement en ligne (PayPal, Direct Debit etc.) selon les options proposées sur le Site concerné. Les prix sont indiqués en Euros TTC (toutes taxes comprises).</p>
                        <p>&nbsp;</p>
                        <p>Vous pouvez mettre à jour votre mode de paiement à tout moment. Love and heart peut également les mettre à jour sur la base d’informations directement fournies par le prestataire de service de paiement. En acceptant les Conditions d’Utilisation, vous autorisez Love and heart à continuer de percevoir le paiement pour chaque renouvellement d’abonnement à la suite de toute mise à jour de votre mode de paiement.</p>
                        <p>Si une Option liée à un Abonnement est souscrite en cours d’Abonnement, l’Abonné bénéficie immédiatement des avantages de l’Option. L’Abonné est alors facturé au prorata pour la période à compter du jour de la souscription de l’Option jusqu’à la fin de l’Abonnement en cours.</p>
                        <p><strong><u>6.2. Modalités de renouvellement de l’Abonnement</u></strong></p>
                        <p>A l’expiration de chaque période de validité, l’Abonnement sera renouvelé par périodes équivalentes à celle initialement choisie, sauf résiliation par l’Abonné dans les conditions indiquées à l’article 9 ci-dessous. Dans certain cas, des périodes de renouvellement plus courtes peuvent s’appliquer telles qu’identifiées sur le Site au moment de la souscription. Lors du renouvellement, l’Abonnement sera facturé à l’Abonné sur la base tarifaire non remisée (plein tarif), Options incluses.</p>
                        <p>En vertu des articles L 215-1 et L241-3 du Code de Consommation, «&nbsp;<em>Pour les contrats de prestations de services conclus pour une durée déterminée avec une clause de reconduction tacite, le professionnel prestataire de services informe le consommateur par écrit, par lettre nominative ou courrier électronique dédiés, au plus tôt trois mois et au plus tard un mois avant le terme de la période autorisant le rejet de la reconduction, de la possibilité de ne pas reconduire le contrat qu’il a conclu avec une clause de reconduction tacite. Cette information, délivrée dans des termes clairs et compréhensibles, mentionne, dans un encadré apparent, la date limite de résiliation. Lorsque cette information ne lui a pas été adressée conformément aux dispositions du premier alinéa, le consommateur peut mettre gratuitement un terme au contrat, à tout moment à compter de la date de reconduction. Les avances effectuées après la dernière date de reconduction ou, s’agissant des contrats à durée indéterminée, après la date de transformation du contrat initial à durée déterminée, sont dans ce cas remboursées dans un délai de trente jours à compter de la date de résiliation, déduction faite des sommes correspondant, jusqu’à celle-ci, à l’exécution du contrat. Les dispositions du présent article s’appliquent sans préjudice de celles qui soumettent légalement certains contrats à des règles particulières en ce qui concerne l’information du consommateur. A défaut de remboursement dans les conditions prévues ci-dessus, les sommes dues sont productives d’intérêts au taux légal&nbsp;</em>».</p>
                        <p>Ainsi, Love and heart informera l’Abonné, par courrier électronique envoyé au plus tôt trois mois et au plus tard un mois avant la fin de l’Abonnement initial, du renouvellement de son Abonnement et, le cas échéant, des Options souscrites, ainsi que de la possibilité de les résilier gratuitement dans les conditions indiquées à l’article 9 des présentes.</p>
                        <p>En outre, une information sur l’échéance de l’Abonnement d’un Abonné est fournie aux Abonnés dans la rubrique «&nbsp;Mon Compte&nbsp;», qui leur permet de gérer leur Abonnement et, le cas échéant, l’annulation du renouvellement automatique.</p>
                        <p><strong><u>Abonnements achetés via l’Apple Store</u></strong></p>
                        <p>Si un Abonné achète un Service payant à renouvellement automatique à l’aide de son identifiant Apple, les conditions de renouvellement sont gérées par Apple selon ses propres conditions générales, sur lesquelles Love and heart n’exerce aucun contrôle.</p>
                        <p><strong><u>6.3. Autres services souscrits auprès de tiers</u></strong></p>
                        <p>L’Abonné peut également souscrire d’autres services ponctuels, tels que l’achat d’applications pour smartphone, voir des offres spéciales. Le cas échéant, ces services ponctuels sont achetés auprès d’autres prestataires et selon d’autres modalités de paiement que celles utilisées pour les Services proposés par Love and heart (par exemple, iTunes pour l’achat d’une application pour iPhone). Les conditions de facturation, les modalités de paiement ainsi que les modalités de renouvellement et de résiliation propres à ces services ponctuels et à ces offres spéciales seront présentées à l’Abonné par le tiers et acceptées par l’Abonné préalablement à son achat.</p>
                        <p>En tout état de cause, l’achat d’applications pour smartphones éditées par Love and heart ne donne en aucun cas accès aux Services Payants sans la souscription d’un Abonnement.</p>
                        <p><strong><u>ARTICLE 7. PROPRIÉTÉ INTELLECTUELLE</u></strong></p>
                        <p><strong><u>7.1. Contenus diffusés sur les Services</u></strong></p>
                        <p>Les dénominations des Services, les marques, les logos, les graphismes, les photographies, les animations, les vidéos et les textes contenus sur les Sites et dans les Services sont la propriété exclusive du Groupe et le cas échéant de ses partenaires et ne peuvent être reproduits, utilisés ou représentés sans l’autorisation expresse des sociétés du Groupe ou de leurs partenaires, sous peine de poursuites judiciaires.</p>
                        <p>Les droits d’utilisation concédés au Membre et à l’Abonné sont réservés à un usage privé et personnel dans le cadre et pour la durée de l’inscription aux Services. Toute autre utilisation par le Membre ou l’Abonné est interdite.</p>
                        <p>Le Membre ou l’Abonné s’interdit notamment de modifier, copier, reproduire, télécharger, diffuser, transmettre, exploiter commercialement et/ou distribuer de quelque façon que ce soit les Services, les pages des Sites, ou les codes informatiques des éléments composant les Services et les Sites, sous peine de poursuites judiciaires.</p>
                        <p><strong><u>7.2. Contenus diffusés par les Membres et Abonnés</u></strong></p>
                        <p>Le Membre ou l’Abonné concède au Groupe une licence d’utilisation des droits de propriété intellectuelle attachés aux contenus fournis par lui dans le cadre de son inscription ou Abonnement et de son utilisation des Services ou de la diffusion de son Profil sur les Services. Cette licence comprend notamment le droit pour le Groupe de reproduire, représenter, adapter, traduire, numériser, utiliser aux fins des Services ou de sous-licencier les contenus fournis par le Membre ou l’Abonné (informations, images, description, critères de recherche, etc.), sur tout ou partie des Services et sur l’ensemble des Sites, dans les mailings des sociétés du Groupe et de manière générale sur tous supports de communication électronique (e-mail, Internet, application mobile) dans le cadre des Services.</p>
                        <p>Le Membre ou l’Abonné autorise expressément le Groupe à modifier lesdits contenus afin de respecter la charte graphique des Services ou des autres supports de communication visés ci-dessus et/ou de les rendre compatibles avec ses performances techniques ou les formats des supports concernés. Ces droits sont concédés pour le monde entier et pour la durée d’exécution des Conditions d’Utilisation entre le Membre ou l’Abonné et Love and heart. Le Membre ou l’Abonné s’interdit de copier, reproduire, ou autrement utiliser les contenus relatifs aux autres Membres et Abonnés autrement que pour les stricts besoins d’utilisation des Services à des fins personnelles et privées.</p>
                        <p><strong><u>ARTICLE 8. RESPONSABILITÉ ET GARANTIE</u></strong></p>
                        <p><strong><u>8.1. Fonctionnement des Sites et des Services</u></strong></p>
                        <p>8.1.1 Pour utiliser les Services, le Membre ou l’Abonné doit disposer des compétences, des équipements et des logiciels requis pour l’utilisation d’Internet ou des applications mobiles des Services. Love and heart met en place des mesures de sécurité dans le cadre de l’utilisation de ses Services. Pour autant, le Membre ou l’Abonné reconnaît que les caractéristiques et les contraintes d’Internet ne permettent pas de garantir une sécurité absolue sur Internet ou via les applications mobiles.</p>
                        <p>8.1.2 Le Membre ou l’Abonné doit posséder l’équipement, en ce inclus les logiciels et les paramétrages adéquats, nécessaires au bon fonctionnement des Services : version la plus récente du navigateur Internet, activation des fonctions Java script, réception de cookies de session et acceptation de l’affichage de fenêtres «&nbsp;pop-ups&nbsp;».</p>
                        <p>8.1.3 Love and heart ne garantit pas que les Services seront utilisables si le Membre ou l’Abonné utilise un utilitaire de «&nbsp;pop-up killer&nbsp;» ou équivalent&nbsp;; dans ce cas, cette fonction devra être désactivée préalablement à l’utilisation des Services.</p>
                        <p>8.1.4 Love and heart ne garantit pas que les Services seront utilisables si le fournisseur d’accès Internet du Membre ou de l’Abonné est défaillant dans l’accomplissement de sa propre prestation. De même, le cas échéant l’utilisation des applications pour smartphones souscrites par le Membre ou l’Abonné directement auprès du fournisseur de l’application suppose que ce dernier dispose d’un smartphone et d’une connexion appropriée.</p>
                        <p>8.1.5 Love and heart n’est pas responsable d’un dysfonctionnement, d’une impossibilité d’accès ou de mauvaises conditions d’utilisation des Sites et Services imputables à un équipement non adapté, à des dysfonctionnements internes au fournisseur d’accès du Membre ou de l’Abonné, à l’encombrement du réseau Internet, et pour toutes autres raisons extérieures à Love and heart ayant le caractère d’un cas de force majeure.</p>
                        <p>8.1.6 L’exploitation des Services pourra être momentanément interrompue pour cause de maintenance, de mise à jour ou d’améliorations techniques, ou pour en faire évoluer le contenu et/ou la présentation. Dans la mesure du possible, Love and heart informera les Membres et Abonnés préalablement à une opération de maintenance ou de mise à jour susceptible d’impacter les Services.</p>
                        <p><strong><u>8.2. Informations et contenus fournis par les Membres</u></strong></p>
                        <p><strong>8.2.1.</strong>&nbsp;Les informations fournies par un Membre ou un Abonné à toute entité du Groupe doivent être exactes et conformes à la réalité. Les conséquences de leur divulgation sur sa vie et/ou celle des autres Membres et Abonnés sont de la responsabilité exclusive du Membre ou de l’Abonné concerné. Le Membre ou l’Abonné prend l’initiative de divulguer et de diffuser via les Services des informations, données, textes, contenus et images le concernant. En conséquence, il renonce à tout recours à l’encontre du Groupe, notamment sur le fondement de l’atteinte éventuelle à son droit à l’image, à son honneur, à sa réputation, à l’intimité de sa vie privée, résultant de la diffusion ou de la divulgation d’informations le concernant dans les conditions prévues par la Politique de Confidentialité dans la mesure où le Membre ou l’Abonné a préalablement, librement et explicitement consenti à une telle divulgation du fait de son inscription ou abonnement aux Services, en application des Conditions d’Utilisation.</p>
                        <p><strong>8.2.2.</strong>&nbsp;Love and heart ne peut être tenue pour responsable de l’exactitude ou de l’inexactitude des informations et contenus fournis par les autres Membres, les autres Abonnés et/ou le Membre ou l’Abonné lui-même, ni des conséquences découlant de l’utilisation de ces informations et contenus. De même, Love and heart ne peut être tenue pour responsable des contenus diffusés par un Membre ou un Abonné susceptibles de contrevenir aux droits d’un ou plusieurs autres Membres, Abonnés ou tiers et dont Love and heart rapporterait la preuve qu’elle n’en aurait pas été informée par un Membre, Abonné ou par un tiers ou n’en aurait pas eu une connaissance effective et préalable avant sa diffusion ou qu’il n’aurait pas commis de faute dans l’exécution de ses obligations contractuelles au titre des Conditions d’Utilisation.</p>
                        <p>Love and heart ne pourra voir sa responsabilité engagée par un Membre ou un Abonné que dans l’hypothèse où la preuve certaine et définitive serait établie d’une faute commise par Love and heart ou par l’un de ses sous-traitants, ayant été la cause exclusive d’un dommage effectif et direct causé au Membre ou à l’Abonné. Le cas échéant, il incombera à Love and heart de démontrer qu’elle n’a pas commis de faute dans l’exécution de ses obligations contractuelles. Love and heart ne sera pas responsable des dommages subis par le Membre ou l’Abonné lorsqu’ils sont causés par ce dernier ou lorsqu’ils résultent d’un cas de force majeure.</p>
                        <p><strong>8.2.3.</strong>&nbsp;La qualité des Services exigée tant par Love and heart que par ses Membres et Abonnés suppose le respect d’une certaine éthique dans l’expression et le comportement des Membres et Abonnés, le respect des droits des tiers, ainsi que le respect des lois et règlements en vigueur. Au service de cette exigence de qualité, de responsabilité individuelle et d’éthique, le Groupe permet à tout Membre et Abonné de lui signaler tous contenus (photographie, texte, vidéo), comportements ou propos d’un Membre ou d’un Abonné qui lui paraissent porter atteinte aux lois et règlements en vigueur, à l’image ou à l’objet des Services, aux droits d’un tiers ou aux bonnes mœurs.</p>
                        <p>En conséquence, les Membres et Abonnés reconnaissent et acceptent que les données qu’ils fournissent, ainsi que leurs comportements ou leurs propos via les Services sont susceptibles de faire l’objet d’un signalement par d’autres Membres ou Abonnés et d’une modération et/ou d’un contrôle par le Groupe, sur la base de critères d’appréciation objectifs. Dans l’hypothèse où ce signalement ou ce contrôle révélerait la violation par un Membre ou par un Abonné des lois et règlements en vigueur ou de ses obligations contractuelles au titre des Conditions d’Utilisation, Love and heart pourra exclure ledit Membre ou Abonné conformément à l’article 9 ci-après. Selon le comportement ou les propos des Membres et Abonnés, l’équipe de surveillance peut prendre la décision de bloquer toute nouvelle inscription par la personne concernée.</p>
                        <p><strong>8.2.4.</strong>&nbsp;Dans le cas où la responsabilité du Groupe serait recherchée à raison d’un manquement par un Membre ou un Abonné aux obligations qui lui incombent aux termes de la loi ou des Conditions d’Utilisation, ce dernier s’engage à garantir le Groupe contre tous dommages, frais ou condamnations prononcés à son encontre trouvant leur origine dans le manquement imputé au Membre ou à l’Abonné.</p>
                        <p><strong><u>8.3. Liens et ressources externes</u></strong></p>
                        <p>Love and heart est uniquement responsable des liens hypertextes qu’elle crée au sein des Sites et Services et n’exerce aucun contrôle des Sites Tiers et des sources externes (sites ou applications mobiles de tiers, réseaux sociaux, etc.) vers lesquels redirigent les liens hypertextes accessibles sur les Sites et les Services. Love and heart ne peut être tenue responsable de la mise à disposition de liens dirigeant vers les Sites Externes et ne peut supporter aucune responsabilité quant aux contenus, publicités, produits, fonctionnalités, services ou autres éléments disponibles sur ou à partir de ces Sites Tiers dont il ne lui aurait pas été fait mention, préalablement et effectivement, de leur caractère manifestement illicite, au moyen d’une notification conforme aux dispositions de l’article 6.I.5 de la loi n°2004-575 tel qu’en vigueur au 1er janvier 2017. Il est rappelé que la consultation et l’utilisation de Sites Tiers sont régies par les conditions d’utilisation de ceux-ci, et qu’elles s’effectuent sous l’entière responsabilité du Membre ou de l’Abonné.</p>
                        <p>Toute difficulté relative à un lien doit être signalée à Love and heart aux coordonnées qui figurent à l’article «&nbsp;Qui sommes-nous&nbsp;?&nbsp;».</p>
                        <p><strong><u>ARTICLE 9. SUSPENSION DU PROFIL – SUPPRESSION DU COMPTE – RÉSILIATION DE L’ABONNEMENT</u></strong></p>
                        <p><strong><u>9.1&nbsp;Suspension du Profil</u></strong></p>
                        <p>Cette section ne s’applique qu’aux Sites pour lesquels cette fonctionnalité est disponible.</p>
                        <p>&nbsp;</p>
                        <p>Chaque Membre ou Abonné peut à tout moment demander la suspension de son Profil, notamment via la rubrique « Mon Compte » dédiée à cet effet, afin de ne plus être visible sur les Sites et ne plus recevoir de notifications. Cette suspension est temporaire et n’interrompt pas l’Abonnement et les éventuelles Options en cours. Le Membre ou l’Abonné peut réactiver son Profil à tout moment.</p>
                        <p><strong><u>9.2 Suppression du Compte</u></strong></p>
                        <p>Chaque Membre ou Abonné peut à tout moment mettre fin à son inscription aux Services ou à son Abonnement en demandant la clôture de son Compte auprès de Love and heart, sans frais autres que ceux liés à la transmission de sa demande et sans motif, notamment via la rubrique «&nbsp;Mon Compte&nbsp;», par email, formulaire de contact ou par tout moyen qui pourra lui être indiqué dans cette rubrique. Cette demande sera réputée effectuée le jour ouvré suivant la réception par Love and heart de la demande de clôture du Compte concerné, et l’Abonné ne pourra plus utiliser son Abonnement et les éventuelles Options en cours. Cette demande ne donne pas droit au remboursement à l’Abonné de la période restant à courir jusqu’à l’échéance de son Abonnement et des éventuelles Options en cours. Le Membre ou l’Abonné sera informé par courrier électronique de la suppression de son Compte.</p>
                        <p><strong><u>9.3 Non-reconduction/Résiliation de l’Abonnement par l’Abonné</u></strong></p>
                        <p>L’Abonné peut mettre fin au renouvellement automatique de son Abonnement 24h après la souscription et jusqu’à 48h au plus tard avant la date d’échéance de l’Abonnement, en se rendant dans la rubrique «&nbsp;Mon Compte&nbsp;». La résiliation prend alors effet à la date d’expiration de l’Abonnement. La résiliation de l’Abonnement sera confirmée à l’Abonné par courrier électronique qui sera utilisé jusqu’à cette date.</p>
                        <p><strong>Services payants achetés via l’Apple Store</strong></p>
                        <p>Si un Abonné a acheté des Services payants à l’aide de son identifiant Apple, les renouvellements automatiques et les résiliations sont gérés par Apple selon ses propres conditions générales, sur lesquelles Love and heart n’exerce aucun contrôle. Pour demander la résiliation d’un Service payant, l’Abonné doit se rendre sur iTunes, cliquer sur son identifiant Apple et suivre les instructions.</p>
                        <p><strong><u>9.4 Résiliation par Love and heart</u></strong></p>
                        <p>Sans préjudice des autres dispositions des Conditions d’Utilisation, en cas de manquement d’un Abonné ou Membre à ses obligations, Love and heart pourra supprimer définitivement le ou les Comptes du Membre ou de l’Abonné concerné au sein de l’ensemble des Sites, révoquer l’accès aux Services et à tout autre service fourni par le Groupe, sans préavis ni mise en demeure. Cette suppression n’emporte le droit au remboursement de l’Abonné. Le Membre ou l’Abonné sera informé par courrier électronique de la suppression de son Compte.</p>
                        <p>Cette suppression interviendra sans préjudice de tous les dommages et intérêts qui pourraient être réclamés par Love and heart au Membre ou à l’Abonné ou ses ayants droit et représentants légaux en réparation des préjudices subis par Love and heart du fait de tels manquements.</p>
                        <p><strong><u>ARTICLE 10.&nbsp;EVENTS ET ACTIVITÉS</u></strong></p>
                        <p>Lorsque des Events ou Activités sont proposés aux Membres et Abonnés sur les Sites, des conditions générales spécifiques sont applicables. Vous pouvez les consulter sur les pages décrivant les Events ou Activités.</p>
                        <p><strong><u>ARTICLE 11. DONNÉES PERSONNELLES</u></strong></p>
                        <p>Les données à caractère personnel des Membres et des Abonnés sont traitées dans le respect de la politique de confidentialité applicable à Love and heart, laquelle est accessible.</p>
                        <p><strong><u>ARTICLE 12. INTÉGRALITÉ DE LA CONVENTION</u></strong></p>
                        <p>Les Conditions d’Utilisation constituent un contrat régissant les relations entre le Membre ou l’Abonné et Love and heart. Elles annulent et remplacent toutes les dispositions antérieures non expressément visées ou annexées et constituent l’intégralité des droits et obligations de Love and heart, des sociétés du Groupe et du Membre ou de l’Abonné relatifs à leur objet.</p>
                        <p>Si une ou plusieurs stipulations des Conditions d’Utilisation étaient déclarées nulles en application d’une loi, d’un règlement ou à la suite d’une décision définitive d’une juridiction ou autorité compétente, les autres stipulations garderont toute leur force et leur portée, dans la mesure permise par la loi, le règlement ou la décision applicable.</p>
                        <p><strong><u>ARTICLE 13. MODIFICATION DES SERVICES ET DES CONDITIONS D’UTILISATION</u></strong></p>
                        <p><strong><u>13.1 Modification des Services</u></strong></p>
                        <p>Love and heart pourra faire évoluer et modifier à tout moment le contenu et/ou les fonctionnalités des Services afin d’en améliorer la qualité. Le Membre ou Abonné sera informé de la nature de ces évolutions ou modifications dès leur mise en ligne sur les Sites.</p>
                        <p><strong><u>13.2 Modification des Conditions d’Utilisation</u></strong></p>
                        <p>Love and heart pourra modifier à tout moment les Conditions d’Utilisation. Le Membre ou l’Abonné sera informé de ces modifications dès leur mise en ligne sur les Sites.</p>
                        <p>Toute nouvelle inscription ou souscription d’Abonnement est soumise aux Conditions d’Utilisation alors en vigueur.</p>
                        <p>Les Abonnés inscrits antérieurement à la modification des Conditions d’Utilisation auront le choix entre deux options&nbsp;:</p>
                        <ul>
                            <li>L’Abonné peut accepter directement les nouvelles Conditions d’Utilisation&nbsp;; celles-ci lui seront opposables à compter de l’acceptation.</li>
                            <li>L’Abonné peut exiger le maintien des Conditions d’Utilisation qui étaient en vigueur lors de la souscription de son Abonnement, jusqu’à l’échéance de l’Abonnement ou des périodes successives de renouvellement tacite de cet Abonnement, en faisant la demande expresse auprès de Love and heart dans un délai d’un (1) mois suivant la date d’entrée en vigueur des Conditions d’Utilisation modifiées, aux coordonnées indiquées à l’article 14 ci-dessous.</li>
                        </ul>
                        <p>A défaut de retour de l’Abonné dans le délai d’un (1) mois après leur entrée en vigueur, les Conditions d’Utilisation modifiées seront réputées acceptées par l’Abonné.</p>
                        <p><strong><u>ARTICLE 14. DEMANDE ET RÉCLAMATION</u></strong></p>
                        <p>Pour toute demande ou réclamation relative à un&nbsp; abonnement,&nbsp; le Membre ou l’Abonné peut contacter Love and heart par courrier postal adressé à Love and heart CS 10002 – 75320 PARIS cedex 09 ou en remplissant le&nbsp;formulaire de contact, en prenant le soin d’indiquer ses identifiants personnels.</p>
                        <p>Le Membre ou Abonné peut également contacter le Service Client par courrier électronique ou par téléphone :</p>
                        <ul>
                            <li>Pour Love and heart : 0615759302, du lundi au vendredi de 9h à 18h/&nbsp;<a href="mailto:contact@love-and-heart.fr">contact@love-and-heart.fr</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary btn-navbar" data-bs-dismiss="modal">Fermer</button>
            </div>
        </div>
    </div>
</div>